import { CarModelData, ColorPreset } from "../types/car";

export const DEFAULT_CAR_MODELS: CarModelData[] = [
  {
    id: "bmw-m4-adro",
    name: "M4 Competition (ADRO Kit)",
    brand: "BMW",
    year: 2022,
    modelPath: "/models/bmw_g82_m4_with_adro_kit_2022__www.vecarz.com.glb",
    category: "Sports Coupe",
    specs: {
      hp: 510,
      zeroToHundred: "3.9s",
      topSpeed: "290 km/h",
      engine: "3.0L Twin-Turbo Inline-6",
    },
    defaultColor: "#1a365d",
  },
  {
    id: "bmw-m4-widebody",
    name: "M4 Carbon Widebody",
    brand: "BMW",
    year: 2022,
    modelPath: "/models/2022_bmw_g82_m4_adro_carbon_fiber_widebody_kit.glb",
    category: "Super Sports",
    specs: {
      hp: 550,
      zeroToHundred: "3.5s",
      topSpeed: "305 km/h",
      engine: "3.0L Tuned Twin-Turbo",
    },
    defaultColor: "#805ad5",
  },
  {
    id: "ferrari-enzo",
    name: "Enzo Ferrari",
    brand: "Ferrari",
    year: 2002,
    modelPath: "/models/ferrari_enzo_2002__www.vecarz.com.glb",
    category: "Hypercar",
    specs: {
      hp: 660,
      zeroToHundred: "3.6s",
      topSpeed: "355 km/h",
      engine: "6.0L Naturally Aspirated V12",
    },
    defaultColor: "#e53e3e",
  },
  {
    id: "ferrari-f50",
    name: "F50",
    brand: "Ferrari",
    year: 1995,
    modelPath: "/models/ferrari_f50_1995__www.vecarz.com.glb",
    category: "Classic Supercar",
    specs: {
      hp: 520,
      zeroToHundred: "3.8s",
      topSpeed: "325 km/h",
      engine: "4.7L V12",
    },
    defaultColor: "#dd6b20",
  },
  {
    id: "mercedes-300sl",
    name: "300SL Gullwing",
    brand: "Mercedes-Benz",
    year: 1954,
    modelPath: "/models/mercedes-benz_300sl_gullwing__www.vecarz.com.glb",
    category: "Vintage Classic",
    specs: {
      hp: 215,
      zeroToHundred: "8.8s",
      topSpeed: "260 km/h",
      engine: "3.0L Inline-6",
    },
    defaultColor: "#e2e8f0",
  },
  {
    id: "mercedes-amg-gt3",
    name: "AMG GT3 EVO",
    brand: "Mercedes-AMG",
    year: 2020,
    modelPath: "/models/mercedes_amg_gt3_evo_2020__www.vecarz.com.glb",
    category: "Race Car",
    specs: {
      hp: 550,
      zeroToHundred: "3.0s",
      topSpeed: "332 km/h",
      engine: "6.2L V8 GT3 Spec",
    },
    defaultColor: "#4a5568",
  },
];

export const COLOR_PRESETS: ColorPreset[] = [
  { name: "Orijinal", hex: "ORIGINAL" },
  { name: "Obsidian Black", hex: "#0f172a" },
  { name: "Alpine White", hex: "#f8fafc" },
  { name: "Monaco Red", hex: "#dc2626" },
  { name: "Riviera Blue", hex: "#0284c7" },
  { name: "Verde Mantis", hex: "#16a34a" },
  { name: "Sunset Orange", hex: "#ea580c" },
  { name: "Ultra Violet", hex: "#7c3aed" },
];
